//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public Employer()
        {
            this.EmployerProjects = new HashSet<EmployerProject>();
            this.Reports = new HashSet<Report>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal Salary { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public int DepartmerntId { get; set; }
    
        public virtual EmployerManager EmployerManager { get; set; }
        public virtual ICollection<EmployerProject> EmployerProjects { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}
