USE [master]
GO
/****** Object:  Database [Teamwork]    Script Date: 8/31/2014 2:25:19 AM ******/
CREATE DATABASE [Teamwork]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Teamwork', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Teamwork.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Teamwork_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Teamwork_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Teamwork] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Teamwork].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Teamwork] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Teamwork] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Teamwork] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Teamwork] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Teamwork] SET ARITHABORT OFF 
GO
ALTER DATABASE [Teamwork] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Teamwork] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Teamwork] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Teamwork] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Teamwork] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Teamwork] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Teamwork] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Teamwork] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Teamwork] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Teamwork] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Teamwork] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Teamwork] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Teamwork] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Teamwork] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Teamwork] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Teamwork] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Teamwork] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Teamwork] SET RECOVERY FULL 
GO
ALTER DATABASE [Teamwork] SET  MULTI_USER 
GO
ALTER DATABASE [Teamwork] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Teamwork] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Teamwork] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Teamwork] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Teamwork] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Teamwork', N'ON'
GO
USE [Teamwork]
GO
/****** Object:  Table [dbo].[Currency]    Script Date: 8/31/2014 2:25:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Currency](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_Currency] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Measure]    Script Date: 8/31/2014 2:25:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Measure](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[measure_name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Measure] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Product]    Script Date: 8/31/2014 2:25:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](150) NULL,
	[price] [real] NOT NULL,
	[quantity] [real] NOT NULL,
	[vendorId] [int] NOT NULL,
	[currencyId] [int] NOT NULL,
	[measureId] [int] NOT NULL,
	[createdDate] [date] NOT NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Town]    Script Date: 8/31/2014 2:25:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Town](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_Town] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Vendor]    Script Date: 8/31/2014 2:25:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vendor](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[vendor_name] [nvarchar](150) NOT NULL,
	[town_id] [int] NOT NULL,
	[vendorTypeId] [int] NOT NULL,
 CONSTRAINT [PK_Vendor] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[VendorType]    Script Date: 8/31/2014 2:25:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VendorType](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_VendorType] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK_Product_Currency] FOREIGN KEY([currencyId])
REFERENCES [dbo].[Currency] ([id])
GO
ALTER TABLE [dbo].[Product] CHECK CONSTRAINT [FK_Product_Currency]
GO
ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK_Product_Measure1] FOREIGN KEY([measureId])
REFERENCES [dbo].[Measure] ([id])
GO
ALTER TABLE [dbo].[Product] CHECK CONSTRAINT [FK_Product_Measure1]
GO
ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK_Product_Vendor] FOREIGN KEY([vendorId])
REFERENCES [dbo].[Vendor] ([id])
GO
ALTER TABLE [dbo].[Product] CHECK CONSTRAINT [FK_Product_Vendor]
GO
ALTER TABLE [dbo].[Vendor]  WITH CHECK ADD  CONSTRAINT [FK_Vendor_Town] FOREIGN KEY([town_id])
REFERENCES [dbo].[Town] ([id])
GO
ALTER TABLE [dbo].[Vendor] CHECK CONSTRAINT [FK_Vendor_Town]
GO
ALTER TABLE [dbo].[Vendor]  WITH CHECK ADD  CONSTRAINT [FK_Vendor_VendorType] FOREIGN KEY([vendorTypeId])
REFERENCES [dbo].[VendorType] ([id])
GO
ALTER TABLE [dbo].[Vendor] CHECK CONSTRAINT [FK_Vendor_VendorType]
GO
USE [master]
GO
ALTER DATABASE [Teamwork] SET  READ_WRITE 
GO
