-- MySQL Script generated by MySQL Workbench
-- 08/23/14 15:47:37
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema UniversitetHW3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `UniversitetHW3` ;
CREATE SCHEMA IF NOT EXISTS `UniversitetHW3` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema universitet
-- -----------------------------------------------------
SHOW WARNINGS;
USE `UniversitetHW3` ;

-- -----------------------------------------------------
-- Table `UniversitetHW3`.`Univeersitet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversitetHW3`.`Univeersitet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UniversitetHW3`.`Univeersitet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UniversitetHW3`.`Facility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversitetHW3`.`Facility` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UniversitetHW3`.`Facility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `Univeersitet_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Facility_Univeersitet_idx` ON `UniversitetHW3`.`Facility` (`Univeersitet_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UniversitetHW3`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversitetHW3`.`Department` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UniversitetHW3`.`Department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `Facility_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Department_Facility1_idx` ON `UniversitetHW3`.`Department` (`Facility_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UniversitetHW3`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversitetHW3`.`Course` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UniversitetHW3`.`Course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Department_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Course_Department1_idx` ON `UniversitetHW3`.`Course` (`Department_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UniversitetHW3`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversitetHW3`.`Profesor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UniversitetHW3`.`Profesor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `Department_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Profesor_Department1_idx` ON `UniversitetHW3`.`Profesor` (`Department_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UniversitetHW3`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversitetHW3`.`Student` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UniversitetHW3`.`Student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `Facility_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Student_Facility1_idx` ON `UniversitetHW3`.`Student` (`Facility_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UniversitetHW3`.`Courses_Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversitetHW3`.`Courses_Students` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UniversitetHW3`.`Courses_Students` (
  `Course_id` INT NOT NULL,
  `Student_id` INT NOT NULL,
  PRIMARY KEY (`Course_id`, `Student_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Course_has_Student_Student1_idx` ON `UniversitetHW3`.`Courses_Students` (`Student_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Course_has_Student_Course1_idx` ON `UniversitetHW3`.`Courses_Students` (`Course_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UniversitetHW3`.`Title`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversitetHW3`.`Title` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UniversitetHW3`.`Title` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UniversitetHW3`.`Profesors_Titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversitetHW3`.`Profesors_Titles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UniversitetHW3`.`Profesors_Titles` (
  `Profesor_id` INT NOT NULL,
  `Title_id` INT NOT NULL,
  PRIMARY KEY (`Profesor_id`, `Title_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Profesor_has_Title_Title1_idx` ON `UniversitetHW3`.`Profesors_Titles` (`Title_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Profesor_has_Title_Profesor1_idx` ON `UniversitetHW3`.`Profesors_Titles` (`Profesor_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
